import type { Metadata } from "next";
import { Roboto, Roboto_Serif } from "next/font/google";
import "./globals.css";
import "../styles/colors.css";
import { ScrollToTop } from "@/components";
import { LanguageProvider } from "@/context/LanguageContext";
import { SpeedInsights } from "@vercel/speed-insights/next";
// Roboto (sans-serif)
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // tuỳ bạn muốn import weight nào
});

// Roboto Serif
const robotoSerif = Roboto_Serif({
  variable: "--font-roboto-serif",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "GhepXe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${robotoSerif.variable} antialiased min-h-screen flex flex-col`}
      >
        <LanguageProvider>
          <ScrollToTop />
          {children}
          <SpeedInsights />
        </LanguageProvider>
      </body>
    </html>
  );
}
